#Expyriment 1.0.0 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Sat Oct 11 2025 21:41:00
#sha1: 9419d2
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='zlr778', release='10', version='10.0.22631', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
2285,design,log,
#design: #exp: Blindspot
#design: block_cnt,block_id,trial_cnt,trial_id
2285,design,logged,
2285,Experiment,started
2286,stderr,received,'Traceback (most recent call last):'
2286,stderr,received,'  File "C:\\Users\\20946\\CogSup\\Programming\\Assignments\\Week-5\\Exercises\\blindspot.py", line 72, in <module>'
2287,stderr,received,'    control.start(subject_id=1)'
2287,stderr,received,'  File "C:\\Users\\20946\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 59, in start'
2299,stderr,received,'    raise Exception("Experiment is already started!")'
2299,stderr,received,'Exception: Experiment is already started!'
